name: WorldCivMaster
main: com.worldciv.the60th.Main
version: 1.0
depend: [WorldGuard, WorldEdit]
commands:
  toggle:
    description:
    usage:
  dungeon:
    description:
    usage:
  dg:
    description:
    usage:
  news:
    description:
    usage:
  party:
    description:
    usage:
  p:
    description:
    usage:
  worldciv:
    description:
    usage:
  wc:
    description:
    usage:
permissions:
  worldciv.togglevision:
    description:
  worldciv.cmds:
    description:
  worldciv.news:
    description:
  worldciv.dungeonadmin:
    description:
  worldciv.admin:
    description:
